name: PUBLISH
on:
  push:
    branches: 
      - main
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest 
    steps:
      - name : checkout
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - name : checkout
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@octocat'
      - name : Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SS }}
